name: Deployemnt to server
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install dependencies
        run: npm i
      - name: build
        run: npm run build

  nginx:
    needs: build
    name: Setup Nginx
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: start the docker with nginx
        run: docker-compose up
